import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const androidServices = JSON.parse(readFileSync("android/app/google-services.json", "utf8"));
const iosServices = readFileSync("ios/FREED/GoogleService-Info.plist", "utf8");
const rootGradle = readFileSync("android/build.gradle", "utf8");
const appGradle = readFileSync("android/app/build.gradle", "utf8");
const podfileProperties = readFileSync("ios/Podfile.properties.json", "utf8");
const androidManifest = readFileSync("android/app/src/main/AndroidManifest.xml", "utf8");
const iosInfo = readFileSync("ios/FREED/Info.plist", "utf8");
const iosEntitlements = readFileSync("ios/FREED/FREED.entitlements", "utf8");
const appConfig = readFileSync("app.config.js", "utf8");
const easConfig = readFileSync("eas.json", "utf8");

assert.equal(androidServices.project_info.project_id, "freed-7d5ee");
assert.equal(androidServices.client[0].client_info.android_client_info.package_name, "app.freed.recovery");
assert.match(iosServices, /<key>PROJECT_ID<\/key>\s*<string>freed-7d5ee<\/string>/);
assert.match(iosServices, /<key>BUNDLE_ID<\/key>\s*<string>app\.freed\.recovery<\/string>/);
assert.match(rootGradle, /com\.google\.gms:google-services/);
assert.match(rootGradle, /com\.google\.firebase:firebase-crashlytics-gradle/);
assert.match(rootGradle, /com\.google\.firebase:perf-plugin/);
assert.match(appGradle, /com\.google\.gms\.google-services/);
assert.match(appGradle, /com\.google\.firebase\.crashlytics/);
assert.match(appGradle, /com\.google\.firebase\.firebase-perf/);
assert.match(podfileProperties, /"ios\.useFrameworks": "static"/);
assert.match(appConfig, /googleServicesFile/);
assert.match(appConfig, /EXPO_PUBLIC_FIREBASE_ENV/);
assert.match(easConfig, /EXPO_PUBLIC_FIREBASE_ENV/);
assert.match(easConfig, /EXPO_PUBLIC_FIREBASE_EMAIL_LINK_DOMAIN.*freed-7d5ee\.firebaseapp\.com/);
assert.match(androidManifest, /firebase_analytics_collection_deactivated" android:value="true"/);
assert.match(androidManifest, /firebase_crashlytics_collection_enabled" android:value="false"/);
assert.match(androidManifest, /firebase_performance_collection_deactivated" android:value="true"/);
assert.match(androidManifest, /firebase_messaging_auto_init_enabled" android:value="false"/);
assert.match(androidManifest, /<intent-filter android:autoVerify="true">[\s\S]*<data android:scheme="https" android:host="freed-7d5ee\.firebaseapp\.com" android:pathPrefix="\/__\/auth\/links"\/>[\s\S]*<\/intent-filter>/);
assert.match(androidManifest, /<data android:scheme="app\.freed\.recovery"\/>/);
assert.match(iosInfo, /<key>FIREBASE_ANALYTICS_COLLECTION_DEACTIVATED<\/key>\s*<true\/>/);
assert.match(iosInfo, /<key>FirebaseCrashlyticsCollectionEnabled<\/key>\s*<false\/>/);
assert.match(iosInfo, /<key>firebase_performance_collection_deactivated<\/key>\s*<true\/>/);
assert.match(iosEntitlements, /<string>applinks:freed-7d5ee\.firebaseapp\.com<\/string>/);
console.log("firebase native integration tests passed");
