apply plugin: "com.android.application"

android {
    namespace "app.freed.qawebview"
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "app.freed.qawebview"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0.0"
    }
}
